# -*- coding: utf-8 -*-
"""Korean-source Localizable keys → English. Merged by fill_en_localizations.py."""

EN_SUPPLEMENT: dict[str, str] = {
    "": "",
    " / 5": " / 5",
    "#%@": "#%@",
    "%": "%",
    "%@": "%@",
    "%@ %@": "%1$@ %2$@",
    "%@ vs %@": "%1$@ vs %2$@",
    "%lld": "%lld",
    "%lld %@": "%1$lld %2$@",
    "%lld - %lld": "%1$lld - %2$lld",
    "%lld : %lld · %@": "%1$lld : %2$lld · %3$@",
    "%lld%%": "%lld%%",
    "%lld/%lld": "%1$lld/%2$lld",
    "%lld개 평가": "%lld ratings",
    "%lld경기": "%lld games",
    "%lld명": "%lld people",
    "%lld승 %lld패": "%1$lldW %2$lldL",
    "%lld승 %lld패 %lld무": "%1$lldW %2$lldL %3$lldD",
    "%lld연속": "%lld straight",
    "%lld연승": "%lld-win streak",
    "%lld월": "Month %lld",
    "%lld장": "%lld photos",
    "%lld회": "%lld×",
    "%lld회 관람": "%lld visits",
    "'%@' 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.": "Delete the ‘%@’ record? This can’t be undone.",
    "+ 버튼을 눌러 첫 관람을 기록해보세요!": "Tap + to log your first visit!",
    "-": "-",
    "100경기 기록 달성": "Logged 100 games",
    "100회 직관": "100 games attended",
    "10경기 기록 달성": "Logged 10 games",
    "10회 직관": "10 games attended",
    "25경기 기록 달성": "Logged 25 games",
    "25회 직관": "25 games attended",
    "3연승 목격": "Witnessed a 3-win streak",
    "50경기 기록 달성": "Logged 50 games",
    "50회 직관": "50 games attended",
    "5연승 목격": "Witnessed a 5-win streak",
    ":": ":",
    "AWAY": "AWAY",
    "D": "D",
    "FANFOLIO": "FANFOLIO",
    "Fanfolio": "Fanfolio",
    "HOME": "HOME",
    "L": "L",
    "LIVE": "LIVE",
    "UPCOMING": "UPCOMING",
    "V.I.P.": "V.I.P.",
    "VS": "VS",
    "W": "W",
    "WIN": "WIN",
    "vs %@": "vs %@",
    "·": "·",
    "· ": "· ",
    "· %@": "· %@",
    "—": "—",
    "⚔️": "⚔️",
    "감상평, 하이라이트, 셋리스트 등": "Thoughts, highlights, setlist, and more",
    "같은 리그 팀을 탭하여 선택하세요.": "Tap a team from the same league.",
    "같은 상대 5경기 이상": "5+ games vs same opponent",
    "결과": "Result",
    "경기": "Game",
    "경기 감상, 하이라이트 등": "Game notes, highlights…",
    "경기 기록": "Game log",
    "경기 상태": "Game status",
    "경기 전이면 '경기 예정', 이미 끝난 경기를 기록하면 '완료'를 선택하세요.": "Use ‘Scheduled’ before the game; choose ‘Completed’ for finished games.",
    "경기 정보": "Game info",
    "경기를 완료로 기록하면 통계가 나타납니다.": "Mark the game completed to see stats.",
    "경기장 사진, 셀카, 음식 등 직관 추억을 기록하세요. (최대 10장)": "Save stadium shots, selfies, food—up to 10 photos.",
    "경기한 두 팀을 각각 탭하여 선택하세요.": "Tap each team that played.",
    "공연장 사진, 셀카, 포토카드 등 추억을 기록하세요. (최대 10장)": "Venue photos, selfies, photocards—up to 10 images.",
    "공유": "Share",
    "공유 미리보기": "Share preview",
    "공유하기": "Share",
    "관람 기록": "Visit log",
    "관람 리포트 공유하기": "Share visit report",
    "관람 마일스톤": "Visit milestones",
    "관람 전에는 '예정', 관람 후에는 '완료'로 변경하세요.": "Set to ‘Scheduled’ before and ‘Completed’ after your visit.",
    "관람 전이면 '예정', 이미 본 공연/영화를 기록하면 '완료'를 선택하세요.": "Use ‘Scheduled’ before; choose ‘Completed’ if you already attended.",
    "관람 통계": "Visit stats",
    "관람을 완료로 기록하면 통계가 나타납니다.": "Mark the visit completed to see stats.",
    "괜찮았어요": "It was okay",
    "국적": "Nationality",
    "기록 삭제": "Delete record",
    "기록 없음": "No records",
    "기록이 없습니다": "No records yet",
    "기록할 경기나 이벤트 이름을 입력하세요.": "Enter a game or event name to log.",
    "기본": "Default",
    "나의 관람 리포트": "My visit report",
    "나의 시즌 리포트": "My season report",
    "나이": "Age",
    "날짜": "Date",
    "날짜 · 장소": "Date · place",
    "내 갤러리에 저장": "Save to my gallery",
    "내 글": "My note",
    "내 팀": "My team",
    "닫기": "Close",
    "달성 뱃지": "Earned badges",
    "등번호": "Number",
    "디자인": "Design",
    "라이벌 마니아": "Rivalry fanatic",
    "만들기": "Create",
    "많음": "High",
    "매우 좋았어요": "Loved it",
    "메모": "Notes",
    "무": "Draw",
    "문화 마니아": "Culture fanatic",
    "문화 애호가": "Culture lover",
    "문화 입문자": "Culture newcomer",
    "문화계의 왕": "Culture champion",
    "별로": "Low",
    "별로였어요": "Didn’t like it",
    "별점 분포": "Rating spread",
    "별점을 선택하세요": "Pick a rating",
    "사진 앱에 저장": "Save to Photos",
    "사진 추가 (%lld/10)": "Add photos (%lld/10)",
    "삭제": "Delete",
    "상대 무득점 승리": "Shutout win",
    "상대 팀": "Opponent",
    "상대별 전적": "Record vs opponent",
    "상위": "Top",
    "상태": "Status",
    "새 폴더": "New folder",
    "선수 정보": "Player info",
    "선수 하이라이트": "Player highlights",
    "선수단 정보를 찾을 수 없습니다": "Roster not found",
    "세로": "Portrait",
    "소감을 적어보세요": "Write your thoughts",
    "소속팀": "Team",
    "스코어": "Score",
    "스타일": "Style",
    "승": "Win",
    "승률": "Win %",
    "시간": "Time",
    "시간 설정": "Set time",
    "시즌 리포트 공유하기": "Share season report",
    "시즌 하이라이트": "Season highlights",
    "아쉬워요": "Too bad",
    "아쉬웠어요": "Disappointing",
    "아티스트 / 출연진": "Artist / cast",
    "아티스트 / 출연진 (선택)": "Artist / cast (optional)",
    "아티스트 / 폴더 이름": "Artist / folder name",
    "아티스트 정보가 있는 기록이 없습니다.": "No records with artist info.",
    "아티스트별 관람": "Visits by artist",
    "연속 3승 달성": "3 wins in a row",
    "연속 5승 달성": "5 wins in a row",
    "연승": "Win streak",
    "연패": "Losing streak",
    "열정적인 관객": "Passionate fan",
    "예: BTS, 위키드, CGV 영화": "e.g. BTS, Wicked, CGV movies",
    "예: LG 트윈스, FC서울": "e.g. LG Twins, FC Seoul",
    "예: 테니스 직관, 마라톤 완주": "e.g. tennis match, marathon finish",
    "예: 테니스 직관, 복싱 경기": "e.g. tennis match, boxing bout",
    "예정": "Scheduled",
    "완료": "Completed",
    "완료된 경기가 없습니다": "No completed games",
    "완료된 기록이 없습니다": "No completed records",
    "완봉승 목격": "Witnessed a complete-game win",
    "원정": "Away",
    "원정 5경기 이상": "5+ away games",
    "원정 경기 기록": "Away-game log",
    "원정 전사": "Road warrior",
    "월별 기록": "By month",
    "이름": "Name",
    "이미지 생성 중...": "Creating image…",
    "이벤트 정보": "Event info",
    "입장 시 이 QR을 스캔하세요": "Scan this QR at entry",
    "자세히 보기": "View details",
    "장소 (선택)": "Venue (optional)",
    "저장": "Save",
    "저장 실패": "Couldn’t save",
    "저장 중...": "Saving…",
    "저장한 티켓": "Saved tickets",
    "적음": "Low",
    "전적 요약": "Record summary",
    "제목": "Title",
    "제목 (예: 위키드 첫 관람)": "Title (e.g. first time seeing Wicked)",
    "좋아하는 아티스트, 작품, 또는 관심사 이름을 입력하세요.": "Enter an artist, show, or interest.",
    "좋았어요": "Good",
    "좌석 정보 (선택)": "Seat info (optional)",
    "직관 마일스톤": "Game-day milestones",
    "직관 사진": "Game photos",
    "직관 사진 추가": "Add game photos",
    "직관 한마디를 적어보세요": "Add a short note from the stands",
    "첫 경기 기록": "First game logged",
    "첫 원정": "First away game",
    "첫 직관": "First game attended",
    "최고!": "Awesome!",
    "최고의 경험!": "Best experience!",
    "최근 12개월": "Last 12 months",
    "최다 관람": "Most visits",
    "최다 대결": "Most matchups",
    "최다 연승": "Longest win streak",
    "최다 연승: %lld연승": "Best streak: %lld wins",
    "최애 선수": "Favorite player",
    "최애 선수 활약": "Favorite’s big night",
    "취소": "Cancel",
    "카테고리 선택": "Choose category",
    "탭하여 확대": "Tap to zoom",
    "통계 계산 중…": "Crunching stats…",
    "티켓 · QR코드": "Ticket · QR",
    "티켓 이미지 공유": "Share ticket image",
    "티켓 이미지 공유하기": "Share ticket image",
    "팀 1": "Team 1",
    "팀 2": "Team 2",
    "팀 라인업": "Lineup",
    "팀 선수단": "Roster",
    "팀 스탯": "Team stats",
    "팀 정보": "Team info",
    "패": "Loss",
    "팬 통계": "Fan stats",
    "팬 퍼센타일": "Fan percentile",
    "편집": "Edit",
    "편집 버튼을 눌러 경기 결과를 입력하세요": "Tap Edit to enter the result.",
    "편집 버튼을 눌러 관람 후 평가를 남겨보세요": "Tap Edit to rate your visit.",
    "평가": "Rating",
    "평균": "Average",
    "평균 별점": "Avg. rating",
    "포지션": "Position",
    "폴더": "Folder",
    "폴더 편집": "Edit folder",
    "한마디": "A word",
    "현장 사진": "Photos",
    "현장 사진 추가": "Add photos",
    "홈": "Home",
    "홈 경기": "Home game",
    "홈 지킴이": "Home guardian",
    "홈경기 10승 이상": "10+ home wins",
    "확인": "OK",
    "회 관람": "visits",
    "💧": "💧",
    "🔥": "🔥",
}
